import {cookies} from "next/headers";
import type {Metadata} from 'next'
import React from 'react';
import {Inter} from 'next/font/google'
import './globals.css'
import {createClient} from "@/src/utils/supabase/server"
import {UserProvider} from "@/src/components/contextProviders/UserProvider";
import { Toaster } from 'react-hot-toast';

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<React.PropsWithChildren> = async ({children}) => {
  const client = createClient(cookies());

  const {data, error} = await client.auth.signInWithPassword({
    email: 'aaa@bbb.com', // hardcoded for now (Task mentioned no need to add login screens)
    password: '123',
  });

  return (
    <html lang="en">
    <body className={inter.className}>
    <Toaster position="top-right"/>
    <UserProvider value={data?.user || null}>
      {children}
    </UserProvider>
    </body>
    </html>
  )
}

export default RootLayout;